# Generated by Django 4.1.1 on 2022-10-31 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_steamname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='steamname',
            new_name='personaname',
        ),
    ]
