# Generated by Django 4.1.1 on 2022-10-19 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0014_gameentry_platforms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.IntegerField(choices=[(0, 'New Status'), (1, 'New Rating'), (2, 'New Review')])),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('new_status', models.IntegerField(blank=True, choices=[(0, 'Wishlist'), (1, 'Backlog'), (2, 'Playing'), (3, 'Completed'), (4, 'Dropped')], null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
