# Generated by Django 4.1.1 on 2022-10-19 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_gameentry_platforms'),
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='game_entry',
            field=models.ForeignKey(default=19, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='games.gameentry'),
            preserve_default=False,
        ),
    ]
