# Generated by Django 4.1.1 on 2022-10-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity_game_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='new_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='new_review',
            field=models.TextField(blank=True),
        ),
    ]
