# Generated by Django 4.1.1 on 2022-10-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activity_new_rating_activity_new_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.IntegerField(choices=[(0, 'New Status'), (1, 'New Rating'), (2, 'New Review'), (3, 'New Game')]),
        ),
    ]
