# Generated by Django 4.1.1 on 2022-10-06 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_cover_game_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='genres',
        ),
    ]
