# Generated by Django 4.1.1 on 2022-10-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_remove_genre_id_remove_platform_id_alter_genre_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(max_length=80, primary_key=True, serialize=False),
        ),
    ]
