# Generated by Django 4.1.1 on 2022-10-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_game_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='franchise',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
