# Generated by Django 4.1.1 on 2022-10-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_game_rating_count_alter_game_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='alternative_names',
            field=models.TextField(blank=True),
        ),
    ]
