# Generated by Django 4.1.1 on 2022-10-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_game_alternative_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameentry',
            name='platforms',
            field=models.ManyToManyField(blank=True, related_name='game_entries', to='games.platform'),
        ),
    ]
