# Generated by Django 4.1.1 on 2022-10-30 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_gameentry_platforms'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='steamappid',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
